name: cs_liveness_flutter
description: A new Flutter plugin project.
version: 1.0.0
homepage: main

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.clearsale.liveness.flutter.cs_liveness_flutter
        pluginClass: CsLivenessFlutterPlugin
      ios:
        pluginClass: CsLivenessFlutterPlugin
